In [1]:
import pandas as pd
import numpy as np
from math import sin, cos, pi, atan2, asin, sqrt, ceil
import matplotlib.pyplot as plt
from model_funcs import *

## "FULLSCALE" 3

In [2]:
SIFT1_datafile = "Full_FS3_SIFT1.csv"
imu_data_file_and_path = "../../" + SIFT1_datafile

final_grid_number = calc_displacement2(imu_data_file_and_path, 210, my_thresh=50, my_post_drogue_delay=0.85, my_signal_length=3, my_t_sim_landing=50, ld_launch_angle=2*pi/180, ld_ssm=3.2, ld_dry_base=15.89)

(array([1384], dtype=int64),)
(array([], dtype=int64),)
Setting maxIndex to -1
Take-Off Time (s) = 0.0
Landing (s) = 73.73000000000002
End time of signal: 11.559999999999945
End time of signal: 14.559999999999945
NUM INT WIND SPEEDS, X->1.9757579530014833 m/s and Y->0.29483364599852413 m/s
---------------------------------------------------------------

Model2 x displacement: 32.42903521913896
Model2 y displacement: 40.07306794568366
AFTER POSSIBLE SIGN FLIP
Model2 x displacement: -32.42903521913896
Model2 y displacement: 40.07306794568366
MODEL 1: TOTAL X AND Y DISPLACEMENTS, u=-1: X->26.328408 m, Y->30.629320 m
MODEL 2: TOTAL X AND Y DISPLACEMENTS, u=-1: X->11.081482680815107 m, Y->44.82383776297116 m

Model2 x displacement: 31.746338810579545
Model2 y displacement: 33.37736844491011
AFTER POSSIBLE SIGN FLIP
Model2 x displacement: -31.746338810579545
Model2 y displacement: -33.37736844491011
MODEL 1: TOTAL X AND Y DISPLACEMENTS, u=0: X->73.367389 m, Y->44.497994 m
MODEL 2: TOTAL X AN

In [3]:
# The actual flight time was ~75 seconds, not 50...
final_grid_number = calc_displacement2(imu_data_file_and_path, 210, my_thresh=50, my_post_drogue_delay=0.85, my_signal_length=3, my_t_sim_landing=75, ld_launch_angle=2*pi/180, ld_ssm=3.2, ld_dry_base=15.89)

(array([2370, 2371], dtype=int64),)
(array([3555, 3556], dtype=int64),)
Take-Off Time (s) = 0.0
Landing (s) = 73.73000000000002
End time of signal: 11.559999999999945
End time of signal: 14.559999999999945
NUM INT WIND SPEEDS, X->1.9757579530014833 m/s and Y->0.29483364599852413 m/s
---------------------------------------------------------------

Model2 x displacement: 32.42903521913896
Model2 y displacement: 40.07306794568366
AFTER POSSIBLE SIGN FLIP
Model2 x displacement: -32.42903521913896
Model2 y displacement: 40.07306794568366
MODEL 1: TOTAL X AND Y DISPLACEMENTS, u=-1: X->26.328408 m, Y->30.629320 m
MODEL 2: TOTAL X AND Y DISPLACEMENTS, u=-1: X->11.081482680815107 m, Y->44.82383776297116 m

Model2 x displacement: 31.746338810579545
Model2 y displacement: 33.37736844491011
AFTER POSSIBLE SIGN FLIP
Model2 x displacement: -31.746338810579545
Model2 y displacement: -33.37736844491011
MODEL 1: TOTAL X AND Y DISPLACEMENTS, u=0: X->73.367389 m, Y->44.497994 m
MODEL 2: TOTAL X AND Y DIS

SIFT2

In [4]:
SIFT2_datafile = "Full_FS3_SIFT2.csv"
imu_data_file_and_path = "../../" + SIFT2_datafile

final_grid_number = calc_displacement2(imu_data_file_and_path, 210, my_thresh=50, my_post_drogue_delay=0.85, my_signal_length=3, my_t_sim_landing=50, ld_launch_angle=2*pi/180, ld_ssm=3.2, ld_dry_base=15.89)

(array([], dtype=int64),)
Setting minIndex to -1
(array([], dtype=int64),)
Setting maxIndex to -1
The predicted flight time is probably wrong


IndexError: index 0 is out of bounds for axis 0 with size 0

In [ ]:
# The actual flight time was ~75 seconds, not 50...
final_grid_number = calc_displacement2(imu_data_file_and_path, 210, my_thresh=50, my_post_drogue_delay=0.85, my_signal_length=3, my_t_sim_landing=75, ld_launch_angle=2*pi/180, ld_ssm=3.2, ld_dry_base=15.89)

## "FULLSCALE" 2

In [ ]:
SIFT2_datafile = "Full_FS2_SIFT2.csv"
imu_data_file_and_path = "../../" + SIFT2_datafile

final_grid_number = calc_displacement2(imu_data_file_and_path, 210, my_thresh=50, my_post_drogue_delay=0.85, my_signal_length=3, my_t_sim_landing=50, ld_launch_angle=2*pi/180, ld_ssm=3.2, ld_dry_base=15.89)

## FULLSCALE 1
> This is for Hoppensville, and we don't have a gridded image for this

In [ ]:
Fullscale1_datafile = "Fullscale1.csv"
imu_data_file_and_path = "../Data/" + Fullscale1_datafile

final_grid_number = calc_displacement2(imu_data_file_and_path, 210, my_thresh=50, my_post_drogue_delay=0.85, my_signal_length=3, my_t_sim_landing=90, ld_launch_angle=2*pi/180, ld_ssm=3.2, ld_dry_base=16.57, ld_m_motor=1.76, ld_t_burn=2.1, ld_T_avg=1740)